Repository CrazySailing/XMLDevourer, pull requests merged in 2021-04, with the labels that each got.

#1 C# project setup
  .gitignore
  XMLDevourer.Tests/UtilsTests.cs
  XMLDevourer.Tests/XMLDevourer.Tests.csproj
  XMLDevourer.sln
  XMLDevourer/Program.cs
  XMLDevourer/Utils.cs
  XMLDevourer/XMLDevourer.csproj
Labels: enhancement, help wanted

#3 Add docker image for development and deployment
  Dockerfile
  README.md
Labels: Ready for review

#11 Add documentation.
  XMLDevourer/Program.cs
Labels: documentation
